# Generated by Django 5.0.6 on 2024-07-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='image',
            field=models.ImageField(null=True, upload_to='users/images'),
        ),
    ]
