# Generated by Django 5.0.6 on 2024-07-12 22:47

import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customusers_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusers',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customusers',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='image',
        ),
        migrations.AddField(
            model_name='customusers',
            name='gender',
            field=models.CharField(choices=[(1, 'M'), (2, 'F')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customusers',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='email',
            field=models.EmailField(max_length=180),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='first_name',
            field=models.CharField(max_length=59),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='last_name',
            field=models.CharField(max_length=59),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='username',
            field=models.CharField(max_length=59, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
