# Generated by Django 5.0.6 on 2024-07-12 22:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customusers_options_alter_customusers_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='users/images'),
            preserve_default=False,
        ),
    ]
