# Generated by Django 5.0.6 on 2024-07-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customusers_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='first_name',
            field=models.CharField(blank=True, max_length=59),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='last_name',
            field=models.CharField(blank=True, max_length=59),
        ),
    ]
