# Generated by Django 5.0.6 on 2024-07-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customusers_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1),
        ),
    ]
