# Generated by Django 5.0.6 on 2024-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customusers_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10),
        ),
    ]
