# Generated by Django 5.0.6 on 2024-07-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_blogpost_images_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
