# Generated by Django 5.0.6 on 2024-07-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
